# Generated by Django 4.0 on 2021-12-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
